version: 2.1
jobs:
  build:
    circleci_ip_ranges: true # opts the job into the IP ranges feature
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - run: echo “Hello World”
workflows:
  build-workflow:
    jobs:
      - build
