version: 2.1

executors:
  ruby:
    docker:
      - image: cimg/ruby:3.2.2

jobs:
  build:
    executor: ruby
    circleci_ip_ranges: true
    steps:
      - run: curl http://checkip.amazonaws.com/
      - run: echo “Hello World”
