version: 2.1

executors:
  default:
    docker:
      - image: cimg/base:stable

jobs:
  build:
    parameters:
      ip-ranges:
        type: boolean
        default: true
    executor: default
    circleci_ip_ranges: << parameters.ip-ranges >> 
    steps:
      - run: curl http://checkip.amazonaws.com/
      - run: echo “Hello World”
